version: '3.8'
services:
    php:
        build:
            context: ./../
            dockerfile: ./docker/local/Dockerfile
        environment:
        volumes:
            - ~/
        ports:
            - '8000:80'
        networks:
            - leads-network
    mysql:
        image: mysql:8
        ports:
        - 3333:3306
        env_file:
            - .dbenv
        volumes:
            - ~/apps/mysql:/var/lib/
        networks:
            - blog-network

networks: 
    blog-network:
        

            
